### ISSUE TITLE
Installation error when is no Husky installed

### ISSUE THREAD

**Issue by voborgus** [sashkopavlenko/serverless-plugin-static#7]
I have no Husky on my project so when I'm running 
```
npm install serverless-plugin-static -D
```
I get the error 
```
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: husky: command not found

```

since it's in the `package.json` file.

**Comment by sashkopavlenko** [comment]
Thanks for reporting this issue! It's been fixed in [0.0.7](https://www.npmjs.com/package/serverless-plugin-static/v/0.0.7).
